Feature/authentication
Compono-Team/I-backend pull request #68
Opened 2024-11-26 08:38 UTC by BomLee427

- 회원가입 -> 카카오 Oauth 구현 완료
- 그 외 공통 상수, 유틸 메서드 등 extract

2024-12-02 12:17 UTC, guscjf0903 reviewed
테스트

2024-12-02 12:17 UTC, guscjf0903 commented on src/main/java/com/compono/ibackend/auth/service/AuthService.java
>          Date now = Date.from(Instant.now());
Date보단 자바 권장이 Instant나 LocalDateTime로 아는데 괜찮을까요?

2024-12-02 12:17 UTC, guscjf0903 commented on src/main/java/com/compono/ibackend/auth/service/AuthService.java
> +        if (!user.getRefreshToken().equals(refreshToken)) {
null.

2024-12-02 12:17 UTC, guscjf0903 requested changes
테스트ㅁㅁ

2024-12-02 12:20 UTC, BomLee427 commented on src/main/java/com/compono/ibackend/auth/service/AuthService.java
>          Date now = Date.from(Instant.now());
JWT 라이브러리 사양때문입니다!

2024-12-02 12:21 UTC, sunsik17 approved these changes
고생하셨습니다.

2024-12-07 10:03 UTC, guscjf0903 approved these changes
고생하셨습니다..! 늦어서 죄송합니다 ㅠㅠ

2024-12-08 12:37 UTC, merged